apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-mgmt
rules:
- apiGroups:
  - ""
  - "kubevirt.io"
  resources:
  - namespaces
  - virtualmachines
  verbs:
  - '*'
